### ISSUE TITLE
ingress route를 통해 forwarding 할 경우 페이지가 로딩 되지 않음

### ISSUE THREAD

**Issue by seungyeop-lee** [kore3lab/kore-dashboard#103]
ingress route 설정을 dashboard에 적용 할 경우 (ex. example.com/kore-board)
js 파일을 불러 올 수 없어서 페이지 로딩이 되지 않습니다.

**Comment by itnpeople** [comment]
아래와 같이 ajax 호출 시 root context 를 반영하는 못하는 것이 원인
* http://example.com/api/clusters/apps-06/nodes (O)
* http://example.com/kore-board/api/clusters/apps-06/nodes (X)
